(function(root){
'use strict';
class BuildingStore {
 constructor(fetcher=fetch){this.fetcher=fetcher;this.token='';this.base='https://api.github.com/repos/gardeliss/themidos';this.sha=null;this.snapshot=null;this.busy=false;}
 headers(){return {Accept:'application/vnd.github+json',...(this.token?{Authorization:'Bearer '+this.token}:{}),'X-GitHub-Api-Version':'2022-11-28'};}
 async request(path,options={}){let r;const controller=new AbortController();const timeout=setTimeout(()=>controller.abort(),15000);try{r=await this.fetcher(this.base+path,{cache:'no-store',...options,signal:controller.signal,headers:{...this.headers(),...options.headers}});}catch(e){throw new Error(e.name==='AbortError'?'Το GitHub δεν απάντησε μέσα σε 15 δευτερόλεπτα. Δοκιμάστε ξανά. Αν συνέβη κατά την αποθήκευση, ανανεώστε πρώτα τα κοινά στοιχεία.':'Ο browser δεν μπόρεσε να επικοινωνήσει με το API του GitHub. Ανοίξτε το https://gardeliss.github.io/themidos/ σε Chrome και δοκιμάστε άλλο δίκτυο. Το κλειδί δεν ελέγχθηκε.');}finally{clearTimeout(timeout);}if(!r.ok){const messages={401:'Το κλειδί πρόσβασης δεν ισχύει ή έχει λήξει.',403:'Δεν επιτρέπεται η ενέργεια. Ελέγξτε Contents: Read and write ή δοκιμάστε αργότερα.',409:'Έγινε άλλη αλλαγή. Ανανεώστε πριν αποθηκεύσετε.',422:'Το GitHub απέρριψε την αποθήκευση.'};throw new Error(messages[r.status]||'Δεν ολοκληρώθηκε η ενέργεια (HTTP '+r.status+').');}return r.json();}
 decode(content){return new TextDecoder().decode(Uint8Array.from(atob(content.replace(/\s/g,'')),c=>c.charCodeAt(0)));}
 encode(text){const bytes=new TextEncoder().encode(text);let result='';for(let i=0;i<bytes.length;i+=8192)result+=String.fromCharCode(...bytes.subarray(i,i+8192));return btoa(result);}
 async read(){const file=await this.request('/contents/data.json?ref=main&t='+Date.now());const value=JSON.parse(this.decode(file.content));if(!value||!['events','contacts','notices','documents'].every(k=>Array.isArray(value[k])))throw new Error('Τα κοινά στοιχεία δεν είναι έγκυρα.');return {value,sha:file.sha};}
 accept(record){this.sha=record.sha;this.snapshot=JSON.stringify(record.value);return record.value;}
 async load(){if(this.token)return this.accept(await this.read());let r;try{r=await this.fetcher('./data.json?t='+Date.now(),{cache:'no-store'});}catch(e){throw new Error('Δεν υπάρχει σύνδεση για φόρτωση των κοινών στοιχείων.');}if(!r.ok)throw new Error('Δεν φορτώθηκαν τα κοινά στοιχεία. Δοκιμάστε ανανέωση.');const value=await r.json();if(!value||!['events','contacts','notices','documents'].every(k=>Array.isArray(value[k])))throw new Error('Τα κοινά στοιχεία δεν είναι έγκυρα.');return this.accept({value,sha:null});}
 async connect(token){if(!/^github_pat_[A-Za-z0-9_]+$/.test(token))throw new Error('Χρησιμοποιήστε fine-grained personal access token από το GitHub.');this.token=token;try{await this.read();}catch(e){this.token='';throw e;}}
 async save(value){if(!this.token)throw new Error('Συνδεθείτε ως διαχειριστής.');if(this.busy)throw new Error('Μια αποθήκευση είναι σε εξέλιξη.');this.busy=true;try{const current=await this.read();if(this.snapshot===null||JSON.stringify(current.value)!==this.snapshot)throw new Error('Τα κοινά στοιχεία άλλαξαν. Πατήστε ανανέωση και ξανακάντε την αλλαγή.');const result=await this.request('/contents/data.json',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:'Update building information',branch:'main',sha:current.sha,content:this.encode(JSON.stringify(value,null,2)+'\n')})});this.sha=result.content.sha;this.snapshot=JSON.stringify(value);return value;}finally{this.busy=false;}}
 async upload(file){if(!this.token)throw new Error('Συνδεθείτε ως διαχειριστής.');if(file.size>5*1024*1024)throw new Error('Μέγιστο μέγεθος αρχείου: 5 MB.');if(!/\.(pdf|png|jpe?g|docx|xlsx|txt)$/i.test(file.name))throw new Error('Επιλέξτε PDF, εικόνα, DOCX, XLSX ή TXT.');const clean=file.name.replace(/[^A-Za-z0-9._-]/g,'_');const path='documents/'+crypto.randomUUID()+'-'+clean;const bytes=new Uint8Array(await file.arrayBuffer());let binary='';for(let i=0;i<bytes.length;i+=8192)binary+=String.fromCharCode(...bytes.subarray(i,i+8192));await this.request('/contents/'+path,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:'Add building document',branch:'main',content:btoa(binary)})});return path;}
}
if(typeof module!=='undefined'&&module.exports)module.exports=BuildingStore;else root.BuildingStore=BuildingStore;
})(globalThis);
